## **General**
1- What's the difference between a Machine Learning (ML) Model and a Machine Learning algorithm.

2- Why we need to study Linear Algebra for ML?

# Responses:
1- a machine learning model is a representation for the process that generate real data, it similiar to mathematical functions with inputs and outputs. So we can call it a predictor algorithm. For ML algorithm is an algorithm that is used to train the model on the datasets.

2- We need to study linear algebra for machine learning beacause we need to represent in a symbolic way the data that we use ( as matrices) and relations between them, we can also try to find similarities between data vectors using linear algebra.

**## Vectors:**

**1- create a vector: **

Our vector can be written as v=(2,1), but more formally we would use the following notation, in which the dimensional coordinate values for the vector are shown as a matrix:$$\vec{v} = \begin{bmatrix}2 \\ 1 \end{bmatrix}$$

In [1]:
import numpy as np
#TO DO...
v = np.array([[2],[1]])

print(v)

[[2]
 [1]]


### **2-Calculating Magnitude**

In [5]:
import math
#TO DO... 
def magnitude(vec):
    sum = 0
    for v in vec: 
      sum += v*v 
    return math.sqrt(sum)
print(magnitude(v))



2.23606797749979



**3- Vector Addition:**
So far, we've worked with one vector at a time. What happens when you need to add two vectors.

Let's take a look at an example, we already have a vector named v, as defined here:$$\vec{v} = \begin{bmatrix}2 \\ 1 \end{bmatrix}$$Now let's create a second vector, and called s like this:$$\vec{s} = \begin{bmatrix}-3 \\ 2 \end{bmatrix}$$

And we have :$$\vec{z} = \vec{v}+\vec{s}$$

In [6]:

import math
import numpy as np

v = np.array([[2],[1]])
s = np.array([[-3],[2]])
z = v + s  
print (z)

[[-1]
 [ 3]]



4- Dot Product Multiplication


$$ \vec{d}=\vec{v} \cdot \vec{s} = (v_{1} \cdot s_{1}) + (v_{2} \cdot s_{2}) ... + \; (v_{n} \cdot s_{n})$$

In [8]:

import math
import numpy as np

v = np.array([[2],[1]])
s = np.array([[-3],[2]])
d = np.vdot(v,s)
print (d)

-4


## **Matrices:**

# 1- create a Matrice:
A matrix arranges numbers into rows and columns, like this:

$$A = \begin{bmatrix}
  1 &amp; 2 &amp; 3 \\
  4 &amp; 5 &amp; 6
 \end{bmatrix}
$$

In [11]:
import numpy as np

A = np.matrix([[1,2,3],[4,5,6]])
print (A)

[[1 2 3]
 [4 5 6]]



#2- Matrix Transposition
You can transpose a matrix, that is switch the orientation of its rows and columns. You indicate this with a superscript T, like this:

$$\begin{bmatrix}1 &amp; 2 &amp; 3 \\4 &amp; 5 &amp; 6\end{bmatrix}^{T} = \begin{bmatrix}1 &amp; 42 &amp; 53 &amp; 6 \end{bmatrix}$$

a- How can we do it mathematically? 

i don't know what you mean by this question, is it about a multiplicatif way to find the transpose ?..........................................



b- with Python: 

In [14]:
import numpy as np

A=np.transpose(A)
print(A)

[[1 4]
 [2 5]
 [3 6]]


## **Eigendecomposition:**

So we've learned a little about eigenvalues and eigenvectors; but you may be wondering what use they are. Well, one use for them is to help decompose transformation matrices.

1- How can we decompose a matrix? ( Rules and steps)
2- (Bonus) Do it in python with your exampls.

1-Finding the egenvalues of the matrix.
2- for each eigenvalue, we try to find the subspace of its vectors and its base vectors.
3- we form the P matrix ( the tranformation from the ordinary base B to the base constracted by the U vi as vi are the vectors of the bases of each eigenvalue
4- we calculate A' = P^(-1) .A . P 

In [ ]:
#2 bonus
import numpy as np